<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getAdminListQuery()
    {
        return $this->createQueryBuilder('p')
            ->select('p, a')
            ->leftJoin('p.author', 'a')
            ->getQuery();
    }
}
