<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function getAdminListQuery()
    {
        return $this->createQueryBuilder('r')
            ->select('r, a')
            ->leftJoin('r.author', 'a')
            ->getQuery();
    }
}
