app_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index }

app_reservation:
    path:     /reservation
    defaults: { _controller: AppBundle:App:reservation }

app_blog_list:
    path:     /blog/{page}
    defaults: { _controller: AppBundle:App:blogList, page: 1 }
    requirements:
        page: \d+

app_blog_post:
    path:     /blog/post/{post}
    defaults: { _controller: AppBundle:App:blogPost }
    requirements:
        id: \d+

app_view_reservations:
   path:     /user/reservations/{page}
   defaults: { _controller: AppBundle:App:viewReservations, page: 1 }
   requirements:
       id: \d+
   options:
       expose: true

app_reservation_api:
    path:     /api/reservation/{date}.json
    defaults: { _controller: AppBundle:App:reservationRequest }
    options:
        expose: true

app_reservation_api_create:
    path:     /api/reservation-create/{name}/{date}/{table}.json
    defaults: { _controller: AppBundle:App:createReservation }
    options:
        expose: true

app_admin:
    prefix: /admin
    resource: 'admin_routing.yml'